[build]
  base = "client"
  publish = "dist"
  command = "nvm install 20.11.1 && nvm use 20.11.1 && npm install -g npm@9.8.1 && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20.11.1"

[[plugins]]
  package = "./netlify/plugins/npm-setup"