[build]
  base = "client"
  publish = "dist"
  command = "npm install -g npm@9.8.1 && npm cache clean --force && rm -rf node_modules package-lock.json && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "9.8.1"